loader:
  data_path: /mnt/e/huggingface/dataset

embedding:
  cache_path: cache/embeddings_cache.json

retriever:
  db_path: chroma_db

database:
  dsn: "host=localhost user=postgres password=020203 dbname=golearn port=5432 sslmode=disable TimeZone=Asia/Shanghai"

jwt:
  hs256_secret: "butterfly"

python_addr: "[::]:50052"